---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
  - namespace.yaml
  - manifests.yaml

configMapGenerator:
- name: docker-registry-config
  files:
  - config.yml
