---
# Cluster Role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-clusterrolebinding
subjects:
- kind: User
  name: "tenant-username"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tenant-clusterrole
  apiGroup: rbac.authorization.k8s.io
