---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - namespace.yaml
  - role-binding.yaml
  - role.yaml
  - monitoring-role-binding.yaml
  - monitoring-role.yaml
  # - resource-quota.yaml
