---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
  - namespace.yaml
  - manifests.yaml
  - mtls-certificate.yaml
  - mtls-issuer.yaml
  - sealed-certs.yaml
