apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: chaos-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    chart: chaos-mesh
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.6.3
    helm:
      releaseName: chaos-mesh
      valuesObject:
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
          # runtime: crio
          # socketPath: /var/run/crio/crio.sock
        webhook:
          certManager:
            # Setup the webhook using cert-manager
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chaos-mesh
