apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: kafka-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: kafka/operator/base
  destination:
    server: https://kubernetes.default.svc
