---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml
- cert-manager-crd.yaml
- chaos-mesh.yaml
- chaos-mesh-crd.yaml
- grafana.yaml
- kafka-crd.yaml
- kafka-operator.yaml
- linkerd.yaml
- linkerd-crd.yaml
- linkerd-viz.yaml
# - minio.yaml # postpone for first apply in order to regenerate sealed-secret
- namespaces.yaml
- openebs.yaml
- openebs-crd.yaml
- otel-collector.yaml
- otel-crd.yaml
- otel-operator.yaml
- prometheus.yaml
- prometheus-crd.yaml
# - registry.yaml # postpone for first apply in order to regenerate sealed-secret
- sealed-secret.yaml
- sealed-secret-crd.yaml
- tempo.yaml
- saiki-tenant.yaml
