---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml
- chaos-mesh.yaml
- grafana.yaml
- kafka-crd.yaml
- kafka-operator.yaml
- minio-secrets.yaml
- minio-tempo.yaml
- minio-mimir.yaml
- namespaces.yaml
- openebs.yaml
- openebs-sc.yaml
- otel-collector.yaml
- otel-crd.yaml
- otel-operator.yaml
- prometheus.yaml
- prometheus-crd.yaml
- registry.yaml # postpone for first apply in order to regenerate sealed-secret
- sealed-secret.yaml
- sealed-secret-crd.yaml
- tempo.yaml # postpone for first apply in order to regenerate sealed-secret
