apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: linkerd/linkerd/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkerd

