apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: minio-mimir
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: minio/mimir
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
