apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-sc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: openebs-sc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: openebs/storage-classes
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
