apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.1.0
    helm:
      releaseName: openebs
      parameters:
      - name: "engines.replicated.mayastor.enabled"
        value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
