apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: openebs/openebs/base
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
