apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: otel-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: otel/operator/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
