apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sealed-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: sealed-secret/sealed-secret/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
