apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sealed-secret-crd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/hanapedia/lab-cluster-apps
    targetRevision: HEAD
    path: sealed-secret/crd/base
  destination:
    server: "https://kubernetes.default.svc"
