apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: tailscale-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.70.0
    helm:
      releaseName: tailscale-operator
      valuesObject:
        apiServerProxyConfig:
          mode: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale

