apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: monitoring

patches:
  - path: mode-patch.yaml
    target:
      group: opentelemetry.io
      version: v1alpha1
      kind: OpenTelemetryCollector
      name: otel-collector
