---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-mimir
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgAO49fyp/In+gZRGhW0uZM9CDpOEjm1sGXRoN4ZVX/ugVIFzLPK254WZW9DlCVkaCrpOdLnrc9Cx1dDjZ/le3KkiVun5b3R3kVTccbLWH4344K5YVAZVaBHKW1xgLf+SJZsOu5nQViTRxQOjrQifuTYfoPfVyjhN/xpRl+9WfeUq+KDGF1YPO6NE5czxhqkGE4Y+aAuAdGjc5TecYom6CZQCOnM5NBExpNgQXEl73UeTuTw227SXvHRzQ9JilZ20wOIazGFtY+xxxmUdtoxL9I9bnUHtBzibCRkT8/JuOp+A3ZCPuHkPbwBOwC8r84CDms95EthuYjQtWUWVSQYwfC6qmcPUAOfNDJ3/gp0uvaL1KTeYUKrgnOlyNOq3bEzt2n/PrEYTxYAfbNLwEivfbYIvn6qfld4FrZLtA1rrhVnvnHBXyVLKjDd2FMYGTr3KS4H4nI/qWdNzbNjNcQskmA7UDvR8AdYocmgFcH3L+ROa/9RNc3VAUij58u3mjksCdNpFugMSgg1Pm61lfy9PuzrqWKiZ0gOKX4AgME9i6iDfX80Heg1GY+6NTbSzOJXfeddLyUeBbNhipy7ZVA9vp12+1tAeW0jnMuAlGxGJwn4irHbnkVmukPL7CgcLl6v+LNoyVYtS5aGNMRKoYNvvkFy/tQ2TBsZmwQLaffaZMqkeeytiNeEVPzBkUMb24krdnQ19z7nFBvDlns=
    rootUser: AgBa8nqtpr077fuZXxurBuhhhDEHvcC0fQiXVziEL7KAwTTG7lrqHcjiPZ07uJkbGbfCHEc6mvlWSbH7N3db6opO9o18MWHVB95BUxHIjfJ37ee+kx2KHFVooNt345icHXYp752/NezUF/yStkmiD4QALekSYElsfMJ67KZb11tbwcScdObJrEedL76FtVtULqjmW6+pQk8YMVEhrbQAt+JNaB9dFJEdvSHQIr1dnG4y5aC6lwb6NU028HU2MpR+Eofrva1y0VdOfZM2kau4GazsF07r+hMgdXaMG1TrTSDlYnw+Ki61gWDXn9Y4oRsoux1NCwyoJIkbBUJkOA9DfUQPlsKTFPR7NIHYyrka7Syd722MT9kD3jKtFRegHrTDlIaTKG7Sq9WCEDgVFpGcjI+ZCnaKcimjucZ+y1V7I7wbDznel4+6xCJ4edOLiHJdWmYNgW0CoAddX+spukIh3S0fbPx6g9Jw6CdvtQele/wlC9cRpDxz72MyXSQ40LE2rHDBsNUKKiv7hctYOG0X9KkEh32wnGSk/RbK95wvoUEEWQj4dUG5jyLWAvZgwO8+axLz4iSa+nI2dvP8HamZ4gLUeuGOOnl8eHGl6VXtZt5zJKvsPMJrwPwm/02StqQc6hoVLj+AhuhQzQMqSKNeqBOK+9Z/65IJM2XisXbmyGecr3YLzoQfJv5tSI4eoQPxb1GvglXSYw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-mimir
      namespace: monitoring
