apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgBvSP42r21dsnLWogdof3zelIbOJpowYPjD327mS/jHXA20JAIt9jLhSfSsmFtgGSzvm54qRTkp6lf0KthAzslVUg6GoatEr0l4i/jzTZeL7/r6GUsP35gkEz7WsjjLB87+7wRNPOO4TOcAY7/rAZvPRzfsPek1aR/RBVONa/KXhw+PuJPEwznDebA3QOx2Hq39JC0MeLAfV4EcCdPIKopVT6TWKnoDmyyKyOMndtbDhW73vkEb6ywq9OhdWz3nnfbTZ1RPxN2d9HrMEmQDr7fGIsBLTGK9o+ZOHVAiakTkPH/H9XS5MQ/XNyxyHSJ/Nfw24/lza6AjBcu6dDS6qFe0McTkkWroB4os5Ehl1Z2nAJkW0rPiALYHzRAsfdzW5E/v8YNTbEdh6EdPUEVCiayBnqW+ziGSKNd63Hvk64FFw6rv+S+ld/WIMBhH7aQNBY5xf+HCg1/yOi0+hDR9VtKskOCBMJjD/tX5TWtaHEOINvzkZ9jg+22Ci72qJrK0wrHStTQ/Hbs2jRLI4U0OHUAHuMH5lYN1GEGmz/giFEVHtPzJv7VXL20VwjoqFwkXJ8HpoR9sRaSRTjezWM/ofWJzdWtMhi1AygCNcwCSy4Q/4LS/wnKMp99NtWEOlVYWktTB1ppvoXZyqNfMrXh7qFvoGuzDzEOFVv2B+WMBqPbplVz/8Wowy5PchtrhKIQU0UvgGvdiT0TFxPqdKRnuAYk=
    username: AgAhJmgL8YF0Lehko49D2zzX2Ys42rdN5X9Rk6BRjdosrm3O9HkZTJWm4HyE2uRCYvPBfpMJdukKxECav2M+0IHRh7P6tnjWpJjG+b/gTXmJdLG3Uo5Vu/mmezTNPztrvNsr0Q9THGpVNNI/lroxe76XNvPZsMuLqqw9D1B68bgVy4c8Mb7FDnXI7ZDKJ11+DUUV1DNfpLVx6V+ltY3pdyMYAcubS2m/AsuNk98JN2z//mQiuqzTjW6lvllP25OIrK00A0rGMkNbViRN6ZRHR89TK3UIp4ZSNBQEC1NIy2KbZJsr8ujWGECb4c7HMzDYEbmKTfjBjYmVsLUUJm1X6mFQupl4Dij4uIMM2bgW8TyJT+Icj4Es/g45NYRLwQo8tOWvmEzB7P+gdkVw0tX69DCPlTu6P/muwyo7BlwttQ+KBcYQkn+3ScMzvYwKP6B6ak9lWOPsAILh0ry6nd4AL1HvU7IZtjpW+NIG81r0gVtcJLsymPEAV2ReK63WJJYJNDbs25w5tidqtMGfwu2ZBjPtQxoPXdFX1MK9P9DshpJAjatJk2vBsMvetcZTBdP0/MsGLDincEHyXhhYgg9jtJabHQZoKJuHP04zvtq52UMjFcGgew4MJ6VCqXJgkjtMNOuyI5sn+LzHRL2QdSFlp4yY/56oxBh5K9qyWOIF1GNt+n7jp3foBHWl3B85rUG4aVbFudqUYwBy+qBYeA/EK2E=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: argocd
    type: Opaque

