---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- manifests.yaml

configMapGenerator:
- name: grafana-datasources
  behavior: create
  files:
  - datasources/datasources.yaml

- name: grafana-dashboards
  behavior: create
  files:
  # - dashboards/node-exporter-full.json
  - dashboards/pod-namespace.json

patches:
- path: datasources-configmap-patch.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: grafana-datasources
- path: dashboards-configmap-patch.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: grafana-dashboards
