apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBephMge/2jSgfv3pWHoWuO7hx8ZfjBMfOnjbmkLAWYGVvOTCJFzfvH6NSYUVAToaiGbwQXWMAlru/1WNfojrszTLrbIIwkwpV139EdDxB2gXSLdMQFX4J8/9/qlPM6CEDbpHBSSOeno+EtN+MiSkn4yoR5P116rMY4ModnO2GBj9CQAaFX2QexXGgNdssK5T1C65ixwwu50YfYMlA6/pQyyCOXYCB0AwxKjd0YFeSMcqQyMqV0aqnLsP7TXSlKvESeQ6NM73sYFEAEq3QHKXfbbWnn9m6E4qvhdX/nKB0Q+t+2P9fU6CDSuosld6DknUgAGpSK9aH5vj3AuytAs53pEncVII4vEa5p8cpqTnCl2fDEP3YVAKxULS1AEg6fnFCtgH3RNrJ6wAoE1tgokVg0xxQOx2Ukhdqzs7zOtPMzsd2AmVHcOaX96G/jNF5pSjvwCWNYmwMexhrvfPN0/Q/EstH6oPMBIWvAWnJNX7JCTJUbRzN198wZakPnio4tFsv6ghbQZezvS7X8Joz/g4kuhw5AqltDovGYpqiPH47mlwW++9sryETzx3uAj8dbgM2zdpdMny8duEu4IwLuehBRqskAlk4ixg7X9vX10G/1QSmTzuJJL6+VebdmX42tWcpqcT/46oODrqVbdzn8E8EV1NjrAYap5LULGyz44pTkVkUhQCVliV6ml/hGhryhva8/x0kwsQ==
    admin-user: AgCiGev+As1eID9kYhKiCqe8i9y1Ftqp42RngKqq5UmjJR/tJF7d/S9zaBKR4gARcMLsFxyXnsM6e4D9wPJaSe5Cf8ZLkaBQEv2I6HsKe9Od1bVs+EhEvxRbe126HK/LHQjYUbR5AQspK+R19sSG/+evLKqmtM9nL9bHm74QzqWtCi7X5gq8pYmaBqVIH5oempCLBiP87ZsRiHmQMuTGyzCLgT1X5OyDt4khKlr+//qP6WuLt700rZAsLLvUCdXKxP1TjKE6Vb09onC8g1db4LShcfSiKF3cD6ZuNquBfII6fWofF5cp0Qun96zC+o+StHSy3fzNGDFPmxDEy06RNFNiwrLzGxW6WWV5vl1MI+3bThNU7/ESd1RbzLQl0xTyaKy/q0iVpBNzVaoVizKTr3yd7nRW6u3skNQFkmBXQFcb/Um4SFSMfIIXUifvRDncv14aKejJyFg8wW2tszvLRgBMzEy2Sjz7yZbGYrS7EIM/A4lxIj4UaOs0wKOhWkM66v0+FYfGyjgV6kSGFdR/y83c+O2OdzId/b1c4WVYxJ4gFbPQvv4itsweLr5tP3Inlrg+fiFqy2b/bPA4HPSUqQTJ/3A0So5gDuwK3PJx47+iX0mulair92UjzyPnq9fIDBf+xs7keHDFHDEQV1stlrlesgsGy2QDVku4NbU9ZfUwsQTiLsouU0xP+U9JuznjkfvW4kAubYo9aA==
    ldap-toml: AgCeWV/bPYkfpwGMwuyoUHB61pFhNyMu7CE/k/S68wrfey4evpTheKjrjmlDX/xb1PmR/Rt37Okq3LPty0cI6mWASLXkuhAPm/p7FXcEUrYmEmBXWUJ7UIVxLTEqqRvOeBpXntKhyl2nJfnai1VNWEkE7+HIhUqO90TEzRNbwvgFX79LKLclIkN+ZsNo5KJc0MoyErD3grHX9MMWoBm0qw4dPUnm2WzhnZ3Mhvz4dPOEubZlrlmiobXAAIBbTcc+xlODDh5VY1LIj7qOlTAS+r7e3EwRLZ0PISV3k+NecSazbV2e/QoYLCp0mA+g9YdYvzK3CYauF0bXbnWKp6gSGo7CDIEuUYYNA28u+Bze6spsaF2ygxN/3NORFFesZ8D+SKt7WPRD2q5LZ7/6LkyxtJfZtCu2brDV5digXmehiNpM6zeDPKAQCg8UpcZZtRopnEUlCum2w6/YZGu7a9h3iJDmkN0ObxhFziffMdmER0ixf4WXmjcUpdjEJQ/n1yzlmNrDef2+ex2Zlbv2bcwTSVGmzKoBi3TaH/cKU6EowQXIeZqKROiPPgxrFa1I+oUezWcLR68yVBBxGEzcXqnul3KgRj8hg6W7tyQR6ytRpgi1WKohXRE54LpT5XfOn5+0+7ZXEuY8+CKizpn+pJKbZukHoV8975vfC4+XGem/J6Jx2GjGeSnI+sPcl0ZC0N5XUgE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

