apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    ldap-toml: AgAep8LcMmG7RZQGU01q7o4jivdXecaUxO6vXMbZ8JUUvWoKdfwJvD7jVdZCy6osIhQyG0ipJNzISj93yc0fdI0/dDjy0Lb0E9c0RsBF53teIn/2Y03wYQOvQIZFy0gDI7O5/VD6ZjXeMwdz5fOlcs0318pYz1Bev6U5hHsKzSYH9KgA7stxVIeFDa1grcy4LMmbppX+BRaN6yxgi66PBgM73/ITsVuAFRTMhu1VNetkJKZxjJQSMmxUSe7vuaj/0kVE4CogDs/oV//WALP65c8W3EdNkS+l7y05N4eCo78RMN21q7YppgNGQhEhEc+SwWEBRK9Hze6S/Rnzqhi3IkeogJn3j5p5WfC22UM47oXpOw4dr2I0g7OE2mxGgdbfdu17Br8shf86KM2AgQP+d89oiOJ6406tcXZt9Ko0MgIu8jZvO+gUbwWztZAvfAhkH+UmSa4669rLdsIygJ2t3tMBKLlX2HFRHNfTnLYSZocCB3lZkSib6JFi+8it/X0qhYgOdl0lIoJpvRdV49BEFyOkQ7cr8bszhrc2BG/s6vu/bjwucwRshm8fgfLQA/CKKdF0Xp0md+c8nc6zAXhVxPzBSXPOZ99/VFfzRUsI5r6m2A10DhvAP/jZteQ4xKINkaz5kZ3SEtgXQboEUloe716NbDgVMkhzlTGZLkpZqHIG9Kcmu7ESPxX6jlbpdKDZRRo=
    password: AgCjZ9qniRRWaeflkRRc7qbewPC5s2e5lTvBaB/3OsR/b/GN9wLdzGrM9WctTERam0tyNA9Yr0y63bRZMX81ZYtnRcgJujJfPzu/7m7+sASuFrAZh9jPn9498fKAzCblpDoVysswTs0eN+WttRmxZCAp+oxWphDSyjTRzVUU76FJm1PCDC5H95pz9qUAaSDQA38OfD4w6I5eG8z0c9y7g5pI+V0HqqczHDTz/qoyTDl60gFkKZZaEx8maqnPsLx9dwA48KXEuw0BH4ane9nL42a4spSBCkv7GomD62KYojPy7yEsVdRORFDEhpzlT9jBJVRMnOisiTf+Uk7KpQPtAKf7pydg8UPbg4DtjwIJ/mmkEbgcPzRoHfWRjD8497dYU8FLs5nx7KCMVfsEL+lwSqzlSLk2DOrx3xf9A0qVzv4odBO3gGeQSKHCrNev2cJ/Nh3Hw5FMRfkj3ygNMK3yI9/hZbvj3cBIJAGh02rXag5AiLgHSD+WDKfF9C1VZ4cWxNumB+T2pMzPIjCt3tYDCu8BRuxOHaEiVN6fjpUToZANLMeW6nqPUUeu4UJcgI+3VCwZ0EMXvEfXNaBcQiVf5Ufue8UIDxot4pxTenRhxdF32xVTCAie5AE4c10I4tLZxe2d/3hTvDAaWsKzPSa1DjJuZdewPPImAmzVlGEE4bzG9TzSYlQS75zQnvSvi9qUeRHmAa9j4Q==
    user: AgBVb6+DXgakiTIv/423FZNrunGDenm+zkB7RJevLvY+/esWTB2hNIkLaPZvXzCEwR3RM3JKVHPMCkMXV5Va1+q6A/ymWuIzPRyC/3iowtR0igq0mvpmMOuDj7oqBWGySnMOgvDT582Zewog0TEI/XPBFo/oFfSv0fTNF04gDzKvbeRYKIhCkRumkCbx09vGZxjITNvi9dpxMhMinY5ioDv1kTYd49n1s8S7D2hyCtfoGCZNTQEs3ZzGaGQHaXgJ0g+QQEMpyUWzWdISR+Dz93+t60If1UxYJQOXXbcft98PrSJxamAi0BivgL7P+eADrQ7xCNDDN+hGSqn4ETPpQBhONdIcRQj4CnnQ/O42c+HCjkHChulJ2VfZpjFbpRlRsue1VlmQJhd9pPXLrAsncQgC/22Xd6EUOyyQGipUfd/+FB5qdhdi0JAT+GYdhMqnfEUdg5HdhKNcuExvyQsY0KOoZInlEOjUaJ/KmvtW9hwxYuksmj3r8MxtZAvNbKRJMg1x+7ci2GH7T1xDdp368JAfvngcAvdfHiZbWMMPIvxKddRgCUoJq1OB11F8LdweVV1bHXktvfd8c3Bry+VE5SOu/2qhXGm5BTcXVId8jao27KvlXF19JioLM3FxVfiSYJewIdMdS98b38JlvBxaaIVvcwk5mR3mxWF0syYCVmlOQ0pdtR0JC1m8lPgIRgOXy/mu9R5ywcOEdQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

