apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCaznitNBRWKablr6E9txApBpGzJxcrC1Je+c7/sCj3Zl3dzdu2vVYxHHUSe2DqpLNdoSzBIWDO0HuIXwP3o+2Cs3p0uMfq3IUHq7hK7o/BuYtGMBUh9Ao9hcY9ho1HH5A/EJL+xgsRm6iUATYHlGpfL6NeA/AQHUC7n0NnizHxQ5AcZkEOKZq/uo9amMmoHW6ZJWK1ZBGya7YBN9t3FM/w8bTz5T89mF2gBpbTzJ4+X8UFebKCrzgml7uJv9RZNQJed7MkLnKx9fpiakg7QX1IH0FtOQS/X6eUDcsc/i9qMZxwjeiMQUOJREMJfpOn83WEV4IgRQACJWpB2JDscu+HC0nvP6WG6vxlq6WQqNkhl4kvi7apoO/oaQboSa/G8DldatWU0OxRYkEBKjhj/g3V/yYmg8ztxk6VmvWiVeBmB6jbF9aCRzhSpceUZWnnUZp5AdQPGwYEuAQsQo9O4OQGPZQhliavStOAHyTYJk1gr1b02NFtnKLMZo5glFt6La70cpl/+cYSVqkgrZhlKItIcZtV3e83CWVlVGxTQIRq/xltGFT0UjpiVkFXgp8xFZ4TW32YYQi79H7BWIogE5PjibjilFu3DHuiX8VnXyyhX7fFTk9mtA3nkp3aKi1sNljpMC65G+FpO2w2PIAPtpRxg1No7q9jnHViDz+9Wk5uq3Rpu/41LqPvhalFRbXf8nVWF+Epew==
    admin-user: AgAZ4+KT2wCY/0L/FsFwLp44/uKniQh6I91cZt++QxYrCNlY6jezt4GpPOgwCPZBSc7j5yOJma7mJBPy4WK65NA76ndkVHznXiQy6ECmNcdx0FXIiiUUBkE/r5mTYCb/Ln1p9Hwng+MuzGP9JGc36lbRVxNuLiMOmLdEnjZXr9DelwVBhQgbuKLBdFwUxqatjyti0c3wYxTRfsAPCLZwaoaEvR1Jg305mMe33RmsSTOq6jHD1xOD/bg8NgN8Ygwwmn5fL+lUEyZq/KqKpdhoajCvwQaf+XiwO8FmUhTNHXmq+Njs0rHba+CL4snbApAya7b7UFHGtKtWz3Ioiw+pdZYhNA46gB2u1Ra+AgRH/AMGPDvLBIBh5/S8ACtQZKUsKpCS8muJ3F15QIUBFYL1jD2JChoDojdrH+FqlAmlSgK6+909EDIT0LU8VD6VpGT5ZzU0QPoWgaIgbf1Eq3cNWtdsxiwG4L7gHXXsgeDaHhSkAzX1nPlBnUg8j5jt/lRXmb8nl75vLUimDpWDXgLUAQGMPGPbBHVeKRpritNPT735Cl+4bkyy4t69E5URD9xUzPdDmxEjepgUXZGN2DkFAbPxzNOmAJU6dxL6U0XLzhh80wrMHrd1CV/CjSkqO8BavQBifTkiIVN7JTbUPUAku7JfE59NPnt2KxvNBgvXtl+nd04+XPmitTLVs7izQLlofwrB+TwONfg=
    ldap-toml: AgA5p+vT1NN3KEIqYL3uEzjlZMDn3Dc0jaP4pCEqXiLlYd2MeHXSMFxxpvcetfqV2aj5ntHej3DSIDBi98sXPKs9b0cLsU6h/6yFiiSjEGpRMU71fwQkPPqWp/YofgHVWWhLl9ApUKC70aVm/wckA5/bfRXNQcaJMBrDPt6/Q+nahajYAzXlUb2pxCFJkJmkljoXMNBhb/lLfP2StQO5tgCwJPGot0TA6kS5wuDLbhug04QC4iAJQRm0V0kZYATqR/RSSDI6rgx5y4YFimybvsst9O4Yhe0W/Td81SN+ZMeNY6CLT/jCGavNbHkdVd6u4i3Mvmiz9J1Jbho+Bi6Et0lcsqTfCZZBxx9yIfjcHiizdobqTy6UMa4DrK2ZJHPwU9hi7HnFWEPB32SP58CP7YDpQJxFVs47YBSTG/hJHbwbNFuVth3VdarbJNw6xaSAPykh4BOhkkGfAdP+0FIDQENDmTwdlTS6nrNvwikbNo6Nrnv/GAb6p7Dx2SblOjB990koVAgqAPquKryTBAUA6chc5LdRceWJRGQ241UkErd+K+cNKR4/Mjch4O8eHA4AiSnMfVCCtFvsFmm7Fz5RGxS7F9mQJJ4V+TPftYJWIpa7CJBDPQMpIbWxuM2m5iR+AuA+Gw7qsNh9Ru+FQCsmfi6U9XsqrK4ebDrgwJM2s6562BrVVE6yQzwU0e9rPTQAFAY=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque

