apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
- name: Tempo
  type: tempo
  url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100
- name: Mimir
  type: prometheus
  url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
