---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgBciDfVvjjTFP7CQVe1QPhxqdMVelsrwqo0iRRy8lPe0heengpvFTBLJOVRjs1Es+Bmd9pQ68rhHjFieqcpGOhQd99VzxjWbMB1gSZcieaBJlCsGieY6XyJYKDCOTwMSkmodT0B/FT4+6aOeqtwu7RgJfW/yG5T7nw6TRQTrl7EMJV8+X5kbihIQm24zJk6Pcj0/H1S6ZdlRqY4u8s3dWotnpZKO0hX87j2U+QqKXbHXZRZFnfu1SIoJYH66JUz8YrazAjK2P/P5hlOayRtxzh0cbP0J/iC4PhvHgLsR3z3SJFYf5CQODBbWwPYf0rae/gpm5S9UyM1eGEGjTCV11nSzEM9CyBgIP2X+PIYdS8G84lXpOH68oEmf9FzXsgh+/joGgDVvIDxvCupjzINriStFQ58JaUbq0dnDJPdKda093507Bosx5Knaag2bTZQxrzsYgJQ/ShouQ6MIygHelOCed7124q3woNTFiKBaOYTg9PRpmoPENbZTojuJp3je+tYzTiNs8uwWHnKzEOHLZJ/19br23qNOswC5R83wh6rJ23p6R3tXLbMnnyOKY/TjgJOEH/MBy7YoVAiyhiqdt0eKIvSh/XCpjmCFr068lL5S9ELtUiWzEUsgUrpO8dzhDuZEmVSh+IRS8oDLLsLh1aRpeZDMJ5IlaTl+YXWjlN0H4g3F9Rznjhp02aPW8zMVwX94OkRhK0vv02B8aQR/W4WWfw=
    clientSecret: AgCAwj5ORD/2k+HpnucUelPsSDnOp+4HuDav1tHfsRVW1PrV1emqV6W4qceDMa1mkapQqKMjV/ZMIOWG4UltPTCCNeyMhCqI8v0PhgoFgqXKw04s7rf58ARYS/EvdIWVtLKPIw+dxT9NVhFg22vUBIG289IlNDZtfP1rb7fZd3kJmMTmmoEKfmSKqmttJZG+NnDgXajChVhZ3ZOW1JEjuSL78iIsbjVSLXQq7f8AgOZQowXK8QTeyrLBbzk8yfdSawifHhHJ+jC47TyL43n9N8m9jpV6RKG/LxrdWu7gMjLPAIWDjkQ11T6piVt5D4AOG9mX47d/JJ9vnSN6Dm4r8dM7uXFdjz+BI621rMtEgKhP65oqZhNI9ytk697nJH084Bzt7mRYYnEUCN+n6dRzON4IW62J20xQrIzz4H+OcK+HU9Lz9gIjdY0U2Hq5ReO2iPXfge30QUl0FSPT6i9HzD9UnOfpVEsAJUDLi0XJjDtkrcw4uBQSBlel55vZ9UATyzxZduildqKK/ZsnZy5FaQhBjGa5uMYqxwCRj9w2Ncdxr5w/6vq5V93nAXB2ZN3m4cQVa/C1c95flAoa2c+nXHi3hUXWyJNUHLlI8WgjdW19iuDCInJ9Ocn2rB98O6E2CBq6WfIXssoA3JGiVZTR0V695uiezwNnDmCNfEzPKg8X+5JkYSGIJONrhYbOE2/AGlH/KwBBhJMibwZNDFOEjB2NmxDJnvMK6b5yYwK7jX7FR18etMGULAjOSiXfif08ZtPKRXioxgcbG0qzgxyVyKI6
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
