apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBuxJUr4xGe52OyHzbIaFTAYwaKtf9TCY5G1MGFVI0Eiaq1eAr+L0MhiMQYvcQtpORggfA8ahyTRA3zWlAoteRRclTJXrZG25lwNlW4lyOIaNF5qXs0mqVTY22yFswQ9fG2w49Xvr61JOuXW7DQAQ6Wjwr1o3nWJsaRXlGSu3ZUwLpMbuhXs1Raj5H/vQsV8f/ehak0JGkCtP+B+h/toegu0IGTaS8/ZOQlYYpmBab0rKknSk10gU2zyz/snBRULq4ezUAr710ulI5ps651vdd8/rCbSYWpfFl9r6Pbs9PXl0LoGu0/21QHbIuhvMpbwz7w07ukbxlYMYFUQYja3UX8ToHDEh4jrYpQMcR7VRbNMOurdm8L5F5Sw6dBMH0gn0MN9DTuUbGrueCvGfJp7Jk7NO2XwyRMXikm/9uL5jdKS2qS+Liw1fNT2FtzcoD1LJhSNbXkkqGG9EvVCoG/IdC/3EGux7+sXngnApWccMe2DoBtX4/nCrm7LagJ7YncwVuRw69VYFctUAPcLEQhKgrI0oIEdHFun4D/SawjZcHQpyxicbO/4Cuw7EgLuqGYqBLzT5hDG4YqEY62Pa679wotO+mEzktZfnrNnH8JMmKs5lPv3FLrAq7W0ZD5B8QwkkeYtkm1Z+tClc/upP7H5wZD3KHEoISz5ymBLmzGD031woR90TrVMgq704XQLWSd/3GMirjbLaOXZeAk2Z/QJrU=
    rootUser: AgBSlY2DH7F3nizajILI65zc9oBSarCeHc83ezeULR4hvSE2PLQ2NiCbdJeysGzkNzFq7PCqC7XhOni4YyK+Ud9MJnWUbnHNx0cAfcqXDFIpfdChlQA5Ony5qy25MXfa5P6RFMQXUGmjb+fw7wdoWRkAPD8VzFYahgMZrDkF99LBxZ9ss+mhtWLb7DbrLlqHgsTpsDrKKYYOGHhtvLyBQ4mPe8Cl+hnCrX/TrX++8Aww0zcFqG6Ys8cq+4/mP+yLatL2ucQZUffrsdYWUNA+dfvFj4pMCBmhckVS4MMGlytWcguOZo+QDyCkC4wVxIF9dzpmi7R5/p190si5sX34TvzWQ/MApHdUPPQhqgkyPTYq9wTqYGd3Fxyu7XD9bcJAYpIOJHQhDpSbQzLRrWDkFWcqowsJY6zd2DsO+CmmTv3DlYK+qeFOljUaObcPKuVCUsWBXEOeWcQqjVdmzvMCm6Pqql6LQluby8ErgcHzbw9Rt7B5qRTvdEyBZi/bl7tQlPdkg2DNgaJTosHURV1p8q7SQfXW2j7ab446rRXAjnAdqPo0v6HXgnuBtLvD4p1msZfv8MyXSHOfS9U1FK8Ii6rAUl2PzBNzZ000omP0DzEJjmyJEff8jU826/voeVaTd47BjBZsy8+HOoRM2dyhMcxJJWSDjKOYfFt9Nh6U39hpTHFWMA3mw2qP/7DdGH1VTyOscM5hxWA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
      name: minio
      namespace: minio
    type: Opaque

