apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCjNT+96xH9mIbDWrbWDbh8xBo2XhvtmTJylb+3Afro0lXI72x5Sl0QhNyn795iPI15k1yqNEW6hi6KVn8shYpHkp4+ONjkfZp5RapUVS6G21EySFNppCJZO+nZP2IfQICZZaDrDRUY3hHdNVXAI+ARNcKe1LgyqLYDdeTf+7l/jZsviBxIATeV/qbkkPikPzdN0nE/SCFXh3pyZb9KAIIAc7FOddsYh34KZqAUFHXWVhLuki7Z3OioblIfnWCJMwjxDI2pJN74CBPs9dvfSvpqyCoxuGH6GWKCLqBEvOK2sCnMXIdNX0F2G+qibdh8EOOjVWwGP1lQ26pvnlRBfKRl1rVnnPZwbqTllEfQFaYrAr7i+2oNh5DnA605o5jl5TFJAshp/f5vBHor19dhQQIsNtabnwVqF7ceBsxRWS46lEMSzfPMiRVKZ5Q3QQqa5bWlAoedlFdWP7RYDs8pZ5JkzWSBVNgHNng0nOJs+gSnajvgry77DYFz3uS5xm7d0MVoBxIgV5eOX50t/F0pu/Ey6S8CtP7pW3U/0JpC6JoPmGCO/1XxiZjS6jmKJTHca87eLAdlBQlUgB9D8vI9uT9RAukP35ziNQEdSoeZcuLF5uLLE1frJFkJ1VSMOt6lcB1hvbRcjZFLyIJZR7R3M2+yR3mpI/mi9eUJ5T46yNyIm5+5VNlcw60AFpN0janMl+vnc6E+jg==
    rootUser: AgBsVTUX6EhnO+Dk0ULn2Whvnb5hdW5ug0qmS58f7Vq8/Ub7M8Iv/jhJpsbstxSlaFIjJDV1834QkdwFrbICM8vxZPsi6Qt89WLYibDwm8x7h3G3jWMm6YSmOZl0MBQH7zRoY3hDCd9nXoodIt4sWs5yMkjcGAlzr8rLyKNVMYSMCM8O31anwnPXL8rLaH6m0oczOMnBHQ0N/qNHqQjRcYbK39bNikcQFTzqTE6hPqYHz93BC0DpW48eZB4+xpujQsA7TdXn50Ia6PnBmWpCADOZ1BHBwjAqGr5vByuFLoJE3ILQe8eqEGeSVYV2EH/kBczmODCU2j9zHHNCHFxFDDzuvC47BzZfWM/sgFzQRw1ixIW7VF2LTmqMcfopdf1pp658THyYNfi62LrxzrF0THobniki4Ix08tOgfghj5nF77NBcd6UPUlvXdWTO8idvBugJrh576ylEPEfKM6OILpRMpF2z8XNv9S1Bp1xuptb479EBeUlN/PF3tY2IsVfOPPRmMUeotOUSmGFLe+GfxfkPRf3wtoxRZlk5jM8cZcWJteeC/dX8ukA2UlKqR7TrgxqUC13tIGCH61PjrjDTnmZND6baq5xqaR1phThzf+GKAkxWw2hL/tP6n2tHrhFbgbqTJk0CBRp6Xn6KENjhEo5b042XcqJdMWsHus+IyzMMNnQ6GfOoXs5g7/iahF8KOZZQ/yEeIDc=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
      name: minio
      namespace: minio
    type: Opaque

