---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-tempo
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgAEyjueWE+5xab/Rv69old9ZWc1jiM3pttkjT3eHAMZJiJKDPbOlXZeJnyxdyq6V9dPJQT1lwaKRDF16IUYqbXh9PVZuYdCqJlM1SpcckUnlUSTSz9eHvUB5vdfhbWNy2DhKos4P0XEJaTy19Q4GseBNXthjutLXCFx1IXcyCgR7iA2SXbh1qV66Va8UFSAod1pfApYVBHZYMb2pyvk3evQ32xag7YuJ84stMgHxjSDGnBji5ucr/ECOcTzKf99fSdvJShuidOCVHL3/ifLsGWGdGLa5X7nMFidxSMwMxtd7d08foweOY5SdQKXQB0UUvhSWe9l8bgAUIEzmYaNvypKXbHmeKcjbb48bIzdM6PlvVxcoPmhnkfltlYkL+Z1S1KYXlX+scP1fGbN52OyC6uwhANPAwHygt3pMUdmZm5dxyfw/ZVE9Bi9+6MFmu2wEa8CbIOdgwlrUfFgdIKzVSmT15KTucmE+01gJfjsE7uErHEqFZLUzHTxTuPXpI1SXYBeFmHhfICwwzJucDBXjE4XTjUdZ0G1l75364y3QJ/P+FxtsO9Wllc/RCTpo8Rprmnw4qAQDAsQRiSpkC5XcscJlTHjcIi7aNhmwf+Q5l67ZGc7N5KqL+K/jurBM2s3YZt29nz/ugWYbFUmXJrLfEG2C7HhmsNHQTLliAhSfDwcM2EOFn2PueffJ2SNGPTk1QE5T0PHodKewbc=
    rootUser: AgAnCPHKdiq1+jTqMuEoW4YB8HjHLPzwhh7ZlV0z1+MLhwednfqQCzrnWp2C+uu9UomyzqBbwxicJH4lbVeBlTC9CNlUUIY9GET44dEqKh5mkdS90FnEBAmo5xSWiBOVVxDLQHCe+/s4Z8NGk6qyISkUEvkJ+7fYUtyXa1FmQKiDHsuN0A7qRfy8NFWUr0Ryuy/zUMCL/32VXVwFyqtTbrae1Ck2Fdu5MaUdJyYcBY+YpmoF4Tyq0Fp2juJFlAP0khIxLIJ2zZufTuFV7HsjoV1jiIv8+CxkGdMWwLXq5T52U0gSq/jpMkBtanFAmrv+6j9v3K04cMDF+aJzzY/vvl9D0JgIDZDN96bUlyaJSugEIRKJOy009xHeDYxoaZBjffodO/3FCv20C3SnrEVxpd7N+xLJTMW4QAF/8oLwfA2Aa/1lMLwBPLgouk2aWnbbJPXzVb47ZJK5TaGLwjGSqoH1PjrBE4NL18OHg6KQDQI4zAgOgwrILvJuW4oryKYTF4gdYRPT88r+L9ivqeDpJTbTdq2dcYuDpbT4IdYjHPwCTScbzQQrna6N4StRVmkBb5rAAtrsy1cQWHvHwcH3Mdma9aCAa4pE9UxI6D49V3EjcXVptUv9aXfUBbK9WepBn6s2w6R5BIyTWbiv9MOkJwPbnlOjsZokmoAAbmdvw3/tTD+IgA4ecsW1BeuFLQ+TM/Zlfg22fg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-tempo
      namespace: monitoring
