---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: example

namePrefix: example-

patches:
  - path: role-binding-patch.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: tenant-rolebinding
  - path: cluster-role-binding-patch.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: tenant-clusterrolebinding
